# This workflow will publish the release as an NPM package

name: Publish NPM package

on:
  release:
    types: [released]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@mapsindoors'
      - run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: npm ci
      - run: npm version --no-git-tag-version --allow-same-version ${{ env.TAG }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
